app/invoice_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("templates/", include("backend.urls.templates_urls")),
    path("htmx/", include("backend.urls.htmx_urls")),
    path("__reload__/", include("django_browser_reload.urls"))
]

app/backend/models.py
import json
from datetime import date, datetime

from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.conf import settings
import uuid

from django.db.models import Max, Sum, F, Count
from django.db.models.functions import TruncMonth, Round
from phonenumber_field.modelfields import PhoneNumberField


def validate_nip(nip):
    if len(nip) != 10 or not nip.isdigit():
        raise ValidationError("NIP musi składać się z 10 cyfr.")
    weights = [6, 5, 7, 2, 3, 4, 5, 6, 7]
    control_sum = sum([int(nip[i]) * weights[i] for i in range(9)])
    if control_sum % 11 != int(nip[9]):
        raise ValidationError("NIP jest nieprawidłowy.")

def validate_regon(regon):
    if len(regon) not in (9, 14) or not regon.isdigit():
        raise ValidationError("REGON musi zawierać 9 lub 14 cyfr.")
    weights_9 = [8, 9, 2, 3, 4, 5, 6, 7]
    weights_14 = [2, 4, 8, 5, 0, 9, 7, 3, 6, 1, 0, 5, 9]

    if len(regon) == 9:
        control_sum = sum([int(regon[i]) * weights_9[i] for i in range(8)])
        if control_sum % 11 != int(regon[8]):
            raise ValidationError("REGON jest nieprawidłowy.")
    elif len(regon) == 14:
        control_sum = sum([int(regon[i]) * weights_14[i] for i in range(13)])
        if control_sum % 11 != int(regon[13]):
            raise ValidationError("REGON jest nieprawidłowy.")


class UUIDModel(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    class Meta:
        abstract = True

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Email is required")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email



class Company(UUIDModel):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='companies',
        blank=False,
        null=False
    )
    name = models.CharField(max_length=225, blank=False)
    nip = models.CharField(
        max_length=10,
        blank=False,
        unique=True,
        validators=[validate_nip]
    )
    regon = models.CharField(max_length=14, blank=True, validators=[validate_regon])
    email = models.EmailField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_latest_invoices(self, limit=10):
        return self.invoices.order_by("-issue_date")[:limit]

    def get_top_clients(self, limit=5):
        return (
            self.clients
            .annotate(total_spent=Sum("invoices__total_gross"))
            .filter(total_spent__isnull=False)
            .order_by("-total_spent")[:limit]
    )

    def get_monthly_revenues(self, year=None):
        if year is None:
            year = datetime.now().year

        monthly_revenues = [0] * 12

        revenues = self.invoices.filter(
            issue_date__year=year
        ).annotate(
            month=TruncMonth('issue_date')
        ).values('month').annotate(
            total_revenue=Sum('total_gross')
        ).order_by('month')

        for revenue in revenues:
            month_index = revenue['month'].month - 1
            monthly_revenues[month_index] = revenue['total_revenue'] or 0

        return monthly_revenues

    def get_monthly_revenues_json(self, year=None):
        return json.dumps(self.get_monthly_revenues(year), default=str)

    def get_current_monthly_revenue(self):
        now = datetime.now()
        monthly_revenues = self.get_monthly_revenues(now.year)
        return monthly_revenues[now.month - 1]

    def get_yearly_revenue(self, year=None):
        if year is None:
            year = datetime.now().year

        return self.invoices.filter(
            issue_date__year=year
        ).aggregate(total_revenue=Sum('total_gross'))['total_revenue'] or 0

    def get_top_products(self, limit=5):
        return (Product.objects.filter(
            invoiceitem__invoice__company=self
        ).annotate(
            total_sold=Sum('invoiceitem__quantity'),
            total_revenue=Round(Sum(
                F('invoiceitem__net_price') * F('invoiceitem__quantity')
            ), 2)
        ).order_by('-total_sold')[:limit])

    def __str__(self):
        return self.name


class Client(UUIDModel):
    company = models.ForeignKey(
        "Company",
        on_delete=models.PROTECT,
        related_name="clients"
    )
    client_company_name = models.CharField(
        max_length=255,
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=100, blank=True, null=True)
    surname = models.CharField(max_length=100, blank=True, null=True)
    nip = models.CharField(max_length=20, blank=True, null=True, validators=[validate_nip])
    regon = models.CharField(max_length=20, blank=True, null=True, validators=[validate_regon])
    email = models.EmailField(blank=True, null=True)
    phone_number = PhoneNumberField(region="PL", blank=True, null=True)

    def __str__(self):
        if self.client_company_name:
            return self.client_company_name
        return f"{self.name} {self.surname or ''}".strip()



class Product(UUIDModel):
    UNIT_CHOICES = [
        ('pcs', 'Sztuki'),
        ('h', 'Godziny'),
        ('kg', 'Kilogramy'),
    ]

    TAX_RATE_CHOICES = [
        (0, '0%'),
        (5, '5%'),
        (8, '8%'),
        (23, '23%'),
        (0, 'zw.')
    ]

    company = models.ForeignKey(
        "Company",
        on_delete=models.PROTECT,
        related_name="products"
    )
    name = models.CharField(max_length=225)
    description = models.TextField(blank=True)
    unit_type = models.CharField(
        max_length=10,
        choices=UNIT_CHOICES,
        default='pcs'
    )
    net_price = models.DecimalField(max_digits=10, decimal_places=2)
    tax_rate = models.IntegerField(
        choices=TAX_RATE_CHOICES,
        default=23
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def calculate_brutto(self):
        return self.net_price * (1 + self.tax_rate / 100)

class Invoice(UUIDModel):
    PAYMENT_METHODS =[
        ('cash', 'Gotówka'),
        ('transfer', 'Przelew Bankowy'),
        ('card', 'Karta Płatnicza'),
    ]

    company = models.ForeignKey(
        "Company",
        on_delete=models.PROTECT,
        related_name='invoices'
    )
    client = models.ForeignKey(
        "Client",
        on_delete=models.SET_NULL,
        null=True,
        related_name='invoices'
    )
    number = models.CharField(max_length=50, unique=True)
    issue_date = models.DateField()
    due_date = models.DateField()
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHODS)
    paid = models.BooleanField(default=False)
    note = models.TextField(blank=True)
    total_net = models.DecimalField(
        max_digits=14,
        decimal_places=2,
        default=0,
        editable=False
    )
    total_tax = models.DecimalField(
        max_digits=14,
        decimal_places=2,
        default=0,
        editable=False
    )
    total_gross = models.DecimalField(
        max_digits=14,
        decimal_places=2,
        default=0,
        editable=False
    )

    def update_totals(self):
        items = self.items.all()
        self.total_net = sum(item.net_total for item in items)
        self.total_tax = sum(item.tax_amount for item in items)
        self.total_gross = sum(item.gross_total for item in items)
        self.save(update_fields=['total_net', 'total_tax', 'total_gross'])

    def generate_invoice_number(self):
        """Generates the invoice number in the format: number/month/year."""
        today = date.today()
        current_month = today.month
        current_year = today.year

        last_invoice = Invoice.objects.filter(
            company=self.company_id,
            issue_date__month=current_month,
            issue_date__year=current_year
        ).aggregate(Max('number'))

        last_number = 0
        if last_invoice['number__max']:
            last_number = int(last_invoice['number__max'].split('/')[0]) + 1

        new_number = last_number + 1

        return f"{new_number}/{current_month:02d}/{current_year}"

    def save(self, *args, **kwargs):
        """Generate an automatic invoice number if number is not set."""
        if not self.number:
            self.number = self.generate_invoice_number()
        super().save(*args, **kwargs)

class InvoiceItem(UUIDModel):
    invoice = models.ForeignKey(
        "Invoice",
        on_delete=models.CASCADE,
        related_name="items"
    )
    product = models.ForeignKey(
        "Product",
        on_delete=models.PROTECT
    )
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    net_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True
    )
    tax_rate = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        blank=True,
        null=True
    )
    net_total = models.DecimalField(max_digits=12, decimal_places=2)

app/backend/views.py
from django.shortcuts import render

# Create your views here.

app/backend/templates/frontend_templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pl" data-theme="magisterka">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Pro Fac{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/dist/styles.css' %}">
  <link rel="icon" type="image/png" href="{% static 'icons/favicon.png' %}">
</head>
<body class="bg-base-200 text-base-content min-h-screen flex flex-col">
  {% include "frontend_templates/partials/navbar.html" %}

  <main class="container mx-auto p-4 sm:p-6 lg:px-12 flex-1 mb-8">
      {% block content %}
      {% endblock %}
  </main>

  {% include "frontend_templates/partials/footer.html" %}

</body></html>

app/backend/templates/frontend_templates/client_create.html
{% extends "frontend_templates/base.html" %}

{% block title %}Dodaj klienta{% endblock %}

{% block content %}
<div class="flex items-center justify-between mb-4">
  <h2 class="text-3xl font-bold">Klienci</h2>
  <a href="{% url 'tmp_clients' %}" class="btn btn-error btn-md shadow-md">
    Wróć do listy klientów
  </a>
</div>

<div class="card bg-base-100 shadow-lg border border-base-300 rounded-box p-6">
  <h2 class="text-2xl font-bold mb-4">Dodaj nowego klienta</h2>
  <form method="POST" class="space-y-4">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit" class="btn btn-primary">Zapisz klienta</button>
  </form>
</div>
{% endblock %}

app/backend/templates/frontend_templates/clients.html
{% extends "frontend_templates/base.html" %}

{% block title %} Klienci {% endblock %}

{% block content %}
<div class="flex items-center justify-between mb-4">
  <h2 class="text-3xl font-bold">Klienci</h2>
  <form method="get" class="flex-grow mx-4 max-w-xs">
    {% if request.GET.sort %}
      <input type="hidden" name="sort" value="{{ request.GET.sort }}">
    {% endif %}

    <div class="join w-full">
      <input type="text"
             name="search"
             class="input input-bordered join-item w-full"
             placeholder="Szukaj i wciśnij Enter..."
             value="{{ request.GET.search|default:'' }}">
      <button type="submit" class="btn btn-primary join-item">Szukaj</button>
    </div>
  </form>
  <a href="{% url 'tmp_client_add' %}" class="btn btn-primary btn-md shadow-md">
    Dodaj klienta
  </a>
</div>

<div class="card bg-base-100 shadow-lg border border-base-300 rounded-box">
  <div class="card-title text-center w-full pt-4 pl-10 pb-4 font-semibold text-lg">
    Lista klientów
    <a
      href="?sort=-id"
      class="btn btn-sm bg-red-500 text-white hover:bg-red-600 ml-4">
      Resetuj filtry
    </a>
  </div>

  <!-- Nagłówki kolumn -->
  <div class="grid grid-cols-5 px-6 pt-4 font-bold text-gray-800 border-t border-gray-300">
    <p class="text-left pl-4">
      <a href="?sort={% if request.GET.sort == 'full_name_or_company' %}-full_name_or_company{% else %}full_name_or_company{% endif %}"
        class="hover:underline">
        Nazwa klienta
        {% if request.GET.sort == 'full_name_or_company' %}
          <span class="text-blue-600">&#8593;</span>
        {% elif request.GET.sort == '-full_name_or_company' %}
          <span class="text-blue-600">&#8595;</span>
        {% else %}
          <span class="text-gray-400">&#8597;</span>
        {% endif %}
      </a>
    </p>
    <p class="text-left">NIP</p>
    <p class="text-left">REGON</p>
    <p class="text-left">
      <a href="?sort={% if request.GET.sort == 'email' %}-email{% else %}email{% endif %}" class="hover:underline">
        Email
        {% if request.GET.sort == 'email' %}
          <span class="text-blue-600">&#8593;</span>
        {% elif request.GET.sort == '-email' %}
          <span class="text-blue-600">&#8595;</span>
        {% else %}
          <span class="text-gray-400">&#8597;</span>
        {% endif %}
      </a>
    </p>
    <p class="text-left">Telefon</p>
  </div>

  <!-- Lista klientów -->
  <div class="card-body p-6 gap-0">
    {% for client in clients %}
    <div class="grid grid-cols-5 items-center border-b border-gray-200 hover:bg-base-300 last:border-b-0 py-4">
      <!-- Nazwa firmy / Imię i nazwisko -->
      <div class="text-left text-sm font-semibold pl-4">
        {% if client.client_company_name %}
        {{ client.client_company_name }}
        {% else %}
        {{ client.name }} {{ client.surname }}
        {% endif %}
      </div>
      <!-- NIP -->
      <div class="text-left text-sm text-gray-700">
        {{ client.nip|default_if_none:"" }}
      </div>
      <!-- REGON -->
      <div class="text-left text-sm text-gray-700">
        {{ client.regon|default_if_none:"" }}
      </div>
      <!-- Email -->
      <div class="text-left text-sm text-gray-700">
        {{ client.email }}
      </div>
      <!-- Telefon -->
      <div class="text-left text-sm text-gray-700">
        {{ client.phone_number }}
      </div>
    </div>

    {% empty %}
    <!-- Gdy brak klientów -->
    <div class="text-gray-500 text-center py-6">
      Brak klientów do wyświetlenia.
    </div>
    {% endfor %}
  </div>
</div>

<!-- Pagination -->
{% if is_paginated %}
<div class="flex justify-center mt-6">
  <div class="btn-group">
    <!-- Button prev -->
    {% if page_obj.has_previous %}
      <a href="?sort={{ request.GET.sort|default:'-id' }}&page={{ page_obj.previous_page_number }}" class="btn btn-sm bg-neutral text-white hover:bg-neutral-focus">← Poprzednia</a>
    {% else %}
      <button class="btn btn-sm btn-disabled">← Poprzednia</button>
    {% endif %}

    <!-- Pagination -->
    {% for page_number in page_obj.paginator.page_range %}
      {% if page_number == page_obj.number %}
        <button class="btn btn-primary btn-md shadow-md hover:bg-primary">{{ page_number }}</button>
      {% else %}
        <a href="?sort={{ request.GET.sort|default:'-id' }}&page={{ page_number }}" class="btn btn-neutral btn-sm shadow-md hover:bg-accent hover:border-accent">{{ page_number }}</a>
      {% endif %}
    {% endfor %}

    <!-- Button next -->
    {% if page_obj.has_next %}
      <a href="?sort={{ request.GET.sort|default:'-id' }}&page={{ page_obj.next_page_number }}" class="btn btn-neutral btn-sm text-white hover:bg-accent hover:border-accent">Następna →</a>
    {% else %}
      <button class="btn btn-sm btn-disabled">Następna →</button>
    {% endif %}
  </div>
</div>
{% endif %}

{% endblock %}

app/backend/templates/frontend_templates/company_create.html
{% extends "frontend_templates/base.html" %}

{% block title %}Dodaj Firmę{% endblock %}

{% block content %}
<div class="flex items-center justify-between mb-4">
  <h2 class="text-3xl font-bold">Firmy</h2>
  <a href="{% url 'tmp_choose_company' %}" class="btn btn-error btn-md shadow-md">
    Wróć do wyboru firmy
  </a>
</div>

<div class="card bg-base-100 shadow-lg border border-base-300 rounded-box p-6">
  <h2 class="text-2xl font-bold mb-4">Dodaj nową firmę</h2>
  <form method="post" class="space-y-4">
    {% csrf_token %}
    {{ form.as_table }}
    <div class="mt-6">
      <button type="submit" class="btn btn-primary btn-md shadow-md">Dodaj firmę</button>
    </div>
  </form>
</div>
{% endblock %}

app/backend/templates/frontend_templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <p>
    {% if user.is_authenticated %}
    Hello {{ user.email }}
    <form method="post" action="{% url 'tmp_logout' %}">
      {% csrf_token %}
      <button type="submit">Logout</button>
    </form>
    {% else %}
    <a href="{% url 'tmp_login' %}">Zaloguj się</a>
    <a href="{% url 'tmp_register' %}">Zarejestruj się</a>
    {% endif %}
  </p>
</body>
</html>

app/backend/templates/frontend_templates/login.html
{% extends "frontend_templates/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Logowanie{% endblock %}

{% block content %}
<div class="container mx-auto max-w-md">
  <h1 class="text-4xl font-bold mb-6 text-center">Zaloguj się</h1>

  <form method="post" class="bg-white p-6 shadow-md rounded-[var(--radius-box)] border border-gray-300">
    {% csrf_token %}

    <div class="mb-4">
      {{ form|crispy }}
    </div>

    <div class="text-center">
      <button type="submit" class="btn btn-primary btn-md shadow-md">
        Zaloguj
      </button>
    </div>
  </form>
</div>
{% endblock %}

app/backend/templates/frontend_templates/product_confirm_delete.html
{% extends "frontend_templates/base.html" %}

{% block title %} Usuń produkt {% endblock %}

{% block content %}
<div class="container mx-auto max-w-md p-6 bg-white shadow-xl rounded-[var(--radius-box)] border border-gray-200">
    <!-- Nagłówek -->
    <h1 class="text-xl font-bold text-center mb-6">
        Czy na pewno chcesz usunąć produkt "{{ object.name }}"?
    </h1>

    <!-- Formularz -->
    <form method="post" class="flex gap-4 justify-center dash">
        {% csrf_token %}
        <button type="submit" class="btn btn-error btn-lg dash">
            Usuń
        </button>
        <a href="{% url 'tmp_products' %}" class="btn btn-secondary btn-lg">
            Anuluj
        </a>
    </form>
</div>
{% endblock %}

app/backend/templates/frontend_templates/product_create.html
{% extends "frontend_templates/base.html" %}

{% block title %}Dodaj Produkt{% endblock %}

{% block content %}
<div class="flex items-center justify-between mb-4">
  <h2 class="text-3xl font-bold">Produkty</h2>
  <a href="{% url 'tmp_products' %}" class="btn btn-error btn-md shadow-md">
    Wróć do listy produktów
  </a>
</div>

<div class="card bg-base-100 shadow-lg border border-base-300 rounded-box p-6">
  <form method="post">
    {% csrf_token %}
    
    <!-- Formularz -->
    <div class="grid gap-4">
      <!-- Renderowanie pól formularza -->
      {{ form.as_table }}
    </div>
    
    <!-- Przycisk 'Dodaj produkt' -->
    <div class="mt-6">
      <button type="submit" class="btn btn-primary btn-md shadow-md">
        {% if view.object.pk %}
          Zapisz zmiany
        {% else %}
          Dodaj produkt
        {% endif %}
      </button>
    </div>
  </form>
</div>
{% endblock %}

app/backend/templates/frontend_templates/product_form.html
{% extends "frontend_templates/base.html" %}

{% block title %} Edycja produktu {% endblock %}

{% block content %}
<h1>Edytuj produkt</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zapisz</button>
</form>
<a href="{% url 'tmp_products' %}">Powrót do listy produktów</a>
{% endblock %}

app/backend/templates/frontend_templates/products.html
{% extends "frontend_templates/base.html" %}
{% block title %}Produkty{% endblock %}
{% block content %}
<div class="flex items-center justify-between mb-4">
  <h2 class="text-3xl font-bold">Produkty</h2>
  <form method="get" class="flex-grow mx-4 max-w-xs">
    {% if request.GET.sort %}
      <input type="hidden" name="sort" value="{{ request.GET.sort }}">
    {% endif %}

    <div class="join w-full">
      <input type="text"
             name="search"
             class="input input-bordered join-item w-full"
             placeholder="Szukaj produktu..."
             value="{{ request.GET.search|default:'' }}">
      <button type="submit" class="btn btn-primary join-item">Szukaj</button>
    </div>
  </form>
  <a href="{% url 'tmp_product_add' %}" class="btn btn-primary btn-md shadow-md">
    Dodaj produkt
  </a>
</div>

<div class="card bg-base-100 shadow-lg border border-base-300 rounded-box">
  <div class="card-title text-center w-full pt-4 pl-10 pb-4 font-semibold text-lg">
    Lista produktów
    <a
      href="?sort=-id"
      class="btn btn-sm bg-red-500 text-white hover:bg-red-600 ml-4">
      Resetuj filtry
    </a>
  </div>

  <!-- Nagłówki kolumn -->
  <div class="grid grid-cols-5 px-6 pt-4 font-bold text-gray-800 border-t border-gray-300">
    <p class="text-left pl-4">
      <a href="?sort={% if request.GET.sort == 'name' %}-name{% else %}name{% endif %}" class="hover:underline">
        Nazwa
        {% if request.GET.sort == 'name' %}
          <span class="text-blue-600">&#8593;</span> <!-- Strzałka w górę -->
        {% elif request.GET.sort == '-name' %}
          <span class="text-blue-600">&#8595;</span> <!-- Strzałka w dół -->
        {% else %}
          <span class="text-gray-400">&#8597;</span> <!-- Neutralna strzałka (domyślne) -->
        {% endif %}
      </a>
    </p>
    <p class="text-left">Opis</p>
    <p class="text-center">
      <a href="?sort={% if request.GET.sort == 'unit_type' %}-unit_type{% else %}unit_type{% endif %}">
        Jednostka
        {% if request.GET.sort == 'unit_type' %}
          <span class="text-blue-600">&#8593;</span>
        {% elif request.GET.sort == '-unit_type' %}
          <span class="text-blue-600">&#8595;</span>
        {% else %}
          <span class="text-gray-400">&#8597;</span>
        {% endif %}
      </a>
    </p>
    <p class="text-right">
      <a href="?sort={% if request.GET.sort == 'net_price' %}-net_price{% else %}net_price{% endif %}" class="hover:underline">
        Cena netto
        {% if request.GET.sort == 'net_price' %}
          <span class="text-blue-600">&#8593;</span>
        {% elif request.GET.sort == '-net_price' %}
          <span class="text-blue-600">&#8595;</span>
        {% else %}
          <span class="text-gray-400">&#8597;</span>
        {% endif %}
      </a>
    </p>
    <p class="text-right">
      <a href="?sort={% if request.GET.sort == 'tax_rate' %}-tax_rate{% else %}tax_rate{% endif %}" class="hover:underline">
        Stawka VAT
        {% if request.GET.sort == 'tax_rate' %}
          <span class="text-blue-600">&#8593;</span>
        {% elif request.GET.sort == '-tax_rate' %}
          <span class="text-blue-600">&#8595;</span>
        {% else %}
          <span class="text-gray-400">&#8597;</span>
        {% endif %}
      </a>
    </p>
  </div>

  <!-- Lista produktów -->
  <div class="card-body pl-6 pr-6 gap-0">
    {% for product in products %}
    <div class="border-b border-gray-200 hover:bg-base-300 last:border-b-0">
      <a href="{% url 'tmp_product_detail' product.pk %}"
         class="hover:underline grid grid-cols-5 items-center py-4">

        <!-- Nazwa produktu -->
        <div class="text-left text-sm font-semibold pl-4">
            {{ product.name }}
        </div>
        <!-- Opis produktu -->
        <div class="text-left text-sm text-gray-700 line-clamp-3">
          {{ product.description }}
        </div>
        <!-- Jednostka miary -->
        <div class="text-center text-sm text-gray-700">
          {{ product.get_unit_type_display }}
        </div>
        <!-- Cena netto -->
        <div class="text-right text-sm text-gray-900 font-bold">
          {{ product.net_price }} zł
        </div>
        <!-- Stawka VAT -->
        <div class="text-right text-sm text-gray-700 pr-4">
          {{ product.tax_rate }}%
        </div>
      </a>
    </div>
    {% empty %}
    <!-- Gdy brak produktów -->
    <div class="text-gray-500 text-center py-6">
      Brak produktów do wyświetlenia
    </div>
    {% endfor %}
  </div>
</div>

<!-- Pagination -->
{% if is_paginated %}
<div class="flex justify-center mt-6">
  <div class="btn-group">
    <!-- Button prev -->
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-sm bg-neutral text-white hover:bg-neutral-focus">← Poprzednia</a>
    {% else %}
      <button class="btn btn-sm btn-disabled">← Poprzednia</button>
    {% endif %}

    <!-- Pagination -->
    {% for page_number in page_obj.paginator.page_range %}
      {% if page_number == page_obj.number %}
        <button class="btn btn-sm bg-primary text-white cursor-default">{{ page_number }}</button>
      {% else %}
        <a href="?page={{ page_number }}" class="btn btn-sm bg-base-300 text-gray-800 hover:bg-primary hover:text-white">{{ page_number }}</a>
      {% endif %}
    {% endfor %}

    <!-- Button next -->
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class="btn btn-sm bg-neutral text-white hover:bg-neutral-focus">Następna →</a>
    {% else %}
      <button class="btn btn-sm btn-disabled">Następna →</button>
    {% endif %}
  </div>
</div>
{% endif %}
{% endblock %}

app/backend/templates/frontend_templates/register.html
{% extends "frontend_templates/base.html" %}
{% block title %}Rejestracja{% endblock %}
{% block content %}
<h1>Rejestracja użytkownika</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Zarejestruj się</button>
    </form>
{% endblock %}